boilerplate_postgres:
  image: "postgres:alpine"
  environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  ports:
    - ${POSTGRES_PORT}:5432
  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data
boilerplate_pgadmin:
  image: "dpage/pgadmin4"
  environment:
    - PGADMIN_DEFAULT_EMAIL=postgres@postgres
    - PGADMIN_DEFAULT_PASSWORD=qwerty
  ports:
    - 8081:80
  volumes:
    - ./volumes/pgadmin:/var/lib/pgadmin